// Sweep EVERY legal species (+ every mega forme reachable through a legal
// stone) for multi-part tactics and write the catalog:
//   data/tactics.champions.json   — machine-readable, top N per pattern
//   docs/notes/tactics.md         — human-readable summary
//
//   npx tsx packages/core/src/scripts/tactics-catalog.ts
//
// Detection is potential-mode (full learnsets, any legal ability/item), so the
// catalog answers "what COULD exist in this format", including off-meta combos
// nobody is running yet — the surprise-factor list.
import { writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadFormat, getItem, getSpecies, dataDirPath } from '../domain/data.js';
import {
  detectTactics, profileFromSpecies, profileFromMegaStone,
  type MonProfile, type TacticInstance,
} from '../domain/tactics.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, '..', '..', '..', '..');

const PER_PATTERN_JSON = 300;
const PER_PATTERN_MD = 12;
const MIN_SCORE = 35;

function buildProfiles(): MonProfile[] {
  const format = loadFormat();
  const profiles: MonProfile[] = [];
  for (const id of format.legality.allow) {
    const sp = getSpecies(id) as { name?: string } | undefined;
    if (!sp?.name) continue;
    profiles.push(profileFromSpecies(sp.name));
  }
  for (const itemId of format.items.allow) {
    const item = getItem(itemId) as { megaStone?: unknown } | undefined;
    if (!item?.megaStone) continue;
    const p = profileFromMegaStone(itemId);
    if (p) profiles.push(p);
  }
  return profiles;
}

function pieceLabel(t: TacticInstance): string {
  return t.pieces.map(p => {
    const bits = [p.species];
    if (p.move) bits.push(p.move);
    if (p.ability) bits.push(`[${p.ability}]`);
    if (p.item) bits.push(`@${p.item}`);
    return bits.join(' ');
  }).join('  +  ');
}

const start = Date.now();
const profiles = buildProfiles();
console.log(`profiles: ${profiles.length} (species + legal mega formes)`);

const all = detectTactics(profiles, { minScore: MIN_SCORE });
console.log(`instances ≥${MIN_SCORE}: ${all.length} in ${Date.now() - start}ms`);

// Group by pattern, keep top N each.
const byPattern = new Map<string, TacticInstance[]>();
for (const t of all) {
  if (!byPattern.has(t.pattern)) byPattern.set(t.pattern, []);
  const arr = byPattern.get(t.pattern)!;
  if (arr.length < PER_PATTERN_JSON) arr.push(t);
}

const jsonOut = {
  __notes: `Generated by tactics-catalog.ts — multi-part tactic sweep of the Champions Reg M-A legal lists. Potential-mode: full learnsets, any legal ability/item. Top ${PER_PATTERN_JSON} per pattern, score ≥${MIN_SCORE}. Regenerate after format changes.`,
  generatedAt: new Date().toISOString(),
  profileCount: profiles.length,
  patterns: Object.fromEntries(
    [...byPattern.entries()].map(([k, v]) => [k, { count: v.length, instances: v }]),
  ),
};
const jsonPath = join(dataDirPath(), 'tactics.champions.json');
writeFileSync(jsonPath, JSON.stringify(jsonOut, null, 1));
console.log(`wrote ${jsonPath}`);

// Markdown summary.
const lines: string[] = [];
lines.push('# Multi-part tactics — Champions Reg M-A');
lines.push('');
lines.push('Generated by `packages/core/src/scripts/tactics-catalog.ts` — do not hand-edit; regenerate after format or detector changes.');
lines.push('');
lines.push(`Sweep of all ${profiles.length} legal species/mega-forme profiles (full learnsets, any legal ability/item). ${all.length} combo instances scored ≥${MIN_SCORE}. Top ${PER_PATTERN_MD} per pattern below; the full set lives in \`data/tactics.champions.json\`.`);
lines.push('');
for (const [pattern, instances] of [...byPattern.entries()].sort((a, b) => b[1][0]!.score - a[1][0]!.score)) {
  const top = instances[0]!;
  lines.push(`## ${top.name.replace(/ \(.*\)$/, '')} (\`${pattern}\`) — ${instances.length} instances`);
  lines.push('');
  lines.push(`*Payoff:* ${top.payoff}`);
  lines.push(`*Counters:* ${top.counters.join('; ')}`);
  lines.push('');
  for (const t of instances.slice(0, PER_PATTERN_MD)) {
    lines.push(`- **${t.score}** ${pieceLabel(t)}`);
  }
  lines.push('');
}
const mdPath = join(repoRoot, 'docs', 'notes', 'tactics.md');
writeFileSync(mdPath, lines.join('\n'));
console.log(`wrote ${mdPath}`);
