import { readFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Dex } from '@pkmn/dex';
import type { ChampionsFormat } from './types.js';
import { _setFormatLoader } from './gimmicks/index.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const dataDir = join(__dirname, '..', '..', '..', '..', 'data');

function loadJsonIfExists<T>(filename: string): Record<string, T> | null {
  const p = join(dataDir, filename);
  if (!existsSync(p)) return null;
  return JSON.parse(readFileSync(p, 'utf8'));
}

// Editable JSON overrides. If a file is missing, fall back to @pkmn/dex directly.
const speciesOverrides = loadJsonIfExists<any>('species.json');
const movesOverrides = loadJsonIfExists<any>('moves.json');
const itemsOverrides = loadJsonIfExists<any>('items.json');
const abilitiesOverrides = loadJsonIfExists<any>('abilities.json');
const naturesOverrides = loadJsonIfExists<any>('natures.json');
// learnsets.json is `{ speciesId: [moveId, ...] }`. Generated by refresh-data
// because @pkmn/dex.learnsets is async, which doesn't compose with our sync
// data accessors elsewhere.
const learnsetsData = loadJsonIfExists<string[]>('learnsets.json');

const gen = Dex.forGen(9);

function toId(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]/g, '');
}

export function getSpecies(name: string) {
  const id = toId(name);
  return speciesOverrides?.[id] ?? gen.species.get(name);
}
export function getMove(name: string) {
  const id = toId(name);
  return movesOverrides?.[id] ?? gen.moves.get(name);
}

// True for moves that charge turn 1 + fire turn 2 (Solar Beam, Electro
// Shot, Sky Attack, Phantom Force, Fly, Dig, Bounce, Meteor Beam, etc.).
// The dex marks these with flags.charge === 1. Power Herb / sun (Solar
// Beam) / electric terrain (Electro Shot) can collapse it to one turn —
// when that happens the user just logs damage normally and the charging
// state never gets set.
export function isChargeMove(name: string): boolean {
  const m = getMove(name) as any;
  return !!(m?.flags?.charge);
}

// True for "pivot" moves that switch the attacker out after resolving
// (U-turn, Volt Switch, Flip Turn, Parting Shot, Teleport, Chilly
// Reception, Baton Pass, Shed Tail). The dex marks these via the
// `selfSwitch` field — `true` for the basic forms, `'copyvolatile'` for
// Baton Pass, `'shedtail'` for Shed Tail. We treat all of them the same
// for prompt purposes (the user picks an incoming mon next).
export function isPivotMove(name: string): boolean {
  const m = getMove(name) as any;
  return !!m?.selfSwitch;
}
// Moves that remove (or consume) the target's held item on hit. Knock Off /
// Thief / Covet / Corrosive Gas strip any item; Incinerate / Bug Bite / Pluck
// destroy a held berry. We mark the target's item as gone for damage-calc
// purposes either way. Trick / Switcheroo SWAP items (not handled here — that
// needs to track the swapped-in item, a separate follow-up).
const ITEM_REMOVING_MOVES = new Set([
  'Knock Off', 'Thief', 'Covet', 'Corrosive Gas', 'Incinerate', 'Bug Bite', 'Pluck',
]);
export function isItemRemovingMove(name: string): boolean {
  return ITEM_REMOVING_MOVES.has(name);
}
export function getItem(name: string) {
  const id = toId(name);
  return itemsOverrides?.[id] ?? gen.items.get(name);
}
export function getAbility(name: string) {
  const id = toId(name);
  return abilitiesOverrides?.[id] ?? gen.abilities.get(name);
}
export function getNature(name: string) {
  const id = toId(name);
  return naturesOverrides?.[id] ?? gen.natures.get(name);
}

export function listSpecies(): string[] {
  if (speciesOverrides) return Object.keys(speciesOverrides);
  return gen.species.all().map(s => s.id as string);
}

// Returns species names (display form) matching the query, restricted to the
// Champions-legal list if one is configured. Prefix matches outrank substring
// matches; ties are alphabetical. Used by the opponent-input autocomplete.
export function searchLegalSpecies(query: string, limit = 8): string[] {
  const format = loadFormat();
  // Expand the allow list with each species's otherFormes so the
  // autocomplete surfaces forme names too (Rotom-Wash, Lycanroc-Midnight,
  // Urshifu-Rapid-Strike, etc.) even though the format file only lists
  // the base species id.
  const legalIds = format.legality.allow.length
    ? expandedLegalIds(format.legality.allow)
    : null;
  const q = toId(query);
  if (!q) {
    // No query: just return the first N legal species alphabetically.
    const ids = legalIds ? [...legalIds] : listSpecies();
    return ids
      .map(id => getSpecies(id)?.name as string | undefined)
      .filter((n): n is string => !!n)
      .sort()
      .slice(0, limit);
  }
  const matches: Array<{ name: string; rank: number }> = [];
  const ids = legalIds ?? new Set(listSpecies());
  for (const id of ids) {
    if (!id.includes(q)) continue;
    const name = getSpecies(id)?.name as string | undefined;
    if (!name) continue;
    const rank = id.startsWith(q) ? 0 : 1;
    matches.push({ name, rank });
  }
  matches.sort((a, b) => a.rank - b.rank || a.name.localeCompare(b.name));
  return matches.slice(0, limit).map(m => m.name);
}

// Cache the expansion since the format file rarely changes and listing
// otherFormes is a per-species dex hit.
let _expandedCache: { srcLen: number; set: Set<string> } | null = null;
function expandedLegalIds(allow: string[]): Set<string> {
  if (_expandedCache && _expandedCache.srcLen === allow.length) {
    return _expandedCache.set;
  }
  const out = new Set<string>();
  for (const raw of allow) {
    const baseId = toId(raw);
    out.add(baseId);
    const sp = getSpecies(baseId) as any;
    const formes: string[] | undefined = sp?.otherFormes;
    // Exclude gimmick formes (Mega-X, Mega-Y, Primal, Gmax, Tera, etc.)
    // from autocomplete — those are battle transformations, not pickable.
    if (formes) for (const f of formes) if (!isGimmickForme(f)) out.add(toId(f));
  }
  _expandedCache = { srcLen: allow.length, set: out };
  return out;
}
export function listMoves(): string[] {
  if (movesOverrides) return Object.keys(movesOverrides);
  return gen.moves.all().map(m => m.id as string);
}
export function listItems(): string[] {
  if (itemsOverrides) return Object.keys(itemsOverrides);
  return gen.items.all().map(i => i.id as string);
}

export function loadFormat(): ChampionsFormat {
  const p = join(dataDir, 'format.champions.json');
  if (!existsSync(p)) {
    return {
      level: 50,
      teamSize: 6,
      bringSize: 4,
      gameType: 'doubles',
      gimmick: 'mega',
      gimmickAllowancePerSide: 1,
      openTeamSheets: true,
      itemClause: true,
      speciesClause: true,
      legality: { allow: [], ban: [] },
      items: { allow: [], ban: [] },
      moves: { ban: [] },
    };
  }
  const raw = JSON.parse(readFileSync(p, 'utf8'));
  // strip __notes if present
  const { __notes: _ignored, ...rest } = raw;
  const fmt = rest as ChampionsFormat;
  // Backfill defaults for fields that may be missing in older format files.
  if (fmt.gimmickAllowancePerSide == null) fmt.gimmickAllowancePerSide = 1;
  return fmt;
}

// Register loadFormat with the gimmick registry so activeGimmick() can resolve
// the configured gimmick without circular imports.
_setFormatLoader(() => loadFormat());

// Returns true for formes that ONLY exist as in-battle transformations —
// Mega Evolution, Primal Reversion, Gigantamax, Tera, etc. These should
// never appear in a team or autocomplete: the user picks the base species,
// equips the appropriate stone/item, and the engine swaps the forme at
// runtime (see gimmicks/mega.ts resolveSpecies).
export function isGimmickForme(speciesIdOrName: string): boolean {
  const sp = getSpecies(speciesIdOrName) as any;
  if (!sp || !sp.exists) return false;
  const forme: string | undefined = sp.forme;
  if (!forme) return false;
  // Match-prefix list so 'Mega', 'Mega-X', 'Mega-Y' all hit.
  return /^(Mega|Primal|Gmax|Tera|Eternamax|Origin|Ultra|Ash)\b/i.test(forme);
}

export function isLegalSpecies(speciesId: string, format = loadFormat()): boolean {
  const id = toId(speciesId);
  if (format.legality.ban.map(toId).includes(id)) return false;
  if (format.legality.allow.length === 0) return true;
  const allow = format.legality.allow.map(toId);
  if (allow.includes(id)) return true;
  // Reject gimmick formes (Mega/Primal/Gmax/Tera/etc.) outright — they're
  // not pickable team members; they're battle transformations.
  if (isGimmickForme(speciesId)) return false;
  // Forme fallback: Rotom-Wash, Lycanroc-Midnight, etc. aren't enumerated
  // in the format file — we resolve them to their base species in the dex
  // and allow if the base is allowed. This covers every Gen 1-9 forme
  // automatically (Rotom-*, Lycanroc-*, Urshifu-*, Landorus-T, etc.).
  const sp = getSpecies(speciesId) as any;
  if (!sp || !sp.exists) return false;
  const base = sp.baseSpecies as string | undefined;
  if (!base) return false;
  const baseId = toId(base);
  if (baseId === id) return false; // already checked above
  return allow.includes(baseId);
}

export function isLegalItem(itemId: string, format = loadFormat()): boolean {
  const id = toId(itemId);
  if (format.items.ban.map(toId).includes(id)) return false;
  if (format.items.allow.length === 0) return true;
  return format.items.allow.map(toId).includes(id);
}

// Display-name move list a species can learn, alphabetical, with format bans
// filtered out. Empty array if the species isn't in the learnset dump.
export function getLearnset(speciesName: string, format = loadFormat()): string[] {
  const id = toId(speciesName);
  const ids = learnsetsData?.[id] ?? [];
  if (!ids.length) return [];
  const bannedIds = new Set(format.moves.ban.map(toId));
  const names: string[] = [];
  for (const moveId of ids) {
    if (bannedIds.has(moveId)) continue;
    const m = getMove(moveId) as any;
    if (m?.name) names.push(m.name);
  }
  names.sort((a, b) => a.localeCompare(b));
  return names;
}

export const dex = gen;
export { toId };
